/* Professional MLBB Coach Engine - analytical inference layer.
   Professional statistics are only used when verified competitive-data.json records exist. */
(() => {
  const PROFILES = {
    Masha:{frontline:7,dive:8,backline:8,sustain:6,mobility:6,split:8,engage:6,cc:2,burst:6,early:6,mid:8,late:7,physical:9,magic:1},
    Fanny:{dive:10,backline:10,mobility:10,burst:9,early:9,mid:9,late:6,objective:6,physical:9,magic:1,frontline:1,cc:2},
    Zhuxin:{cc:8,zone:9,poke:7,waveclear:8,magic:10,teamfight:9,engage:5,disengage:8,mid:9,late:8},
    Nolan:{dive:9,backline:9,mobility:9,burst:9,early:8,mid:9,late:6,objective:7,physical:9,magic:1},
    Carmilla:{frontline:8,engage:9,cc:9,teamfight:10,sustain:7,peel:7,magic:5},
    Aulus:{sustained:9,late:10,objective:8,physical:10,frontline:5,early:4,mid:6,mobility:5},
    Bruno:{burst:8,sustained:9,late:9,objective:8,physical:10,range:7},
    Claude:{sustained:9,mobility:9,teamfight:9,late:9,physical:9,backline:6,objective:7},
    Lylia:{poke:8,waveclear:9,disengage:9,magic:10,early:8,mid:8,late:7,mobility:7,zone:8},
    Uranus:{frontline:9,sustain:10,split:8,disengage:7,late:8,magic:4,physical:3},
    Atlas:{engage:10,cc:10,teamfight:10,frontline:8,peel:6}, Minotaur:{engage:9,cc:9,frontline:9,sustain:7,peel:8,teamfight:9},
    Gloo:{frontline:9,sustain:9,cc:7,disrupt:9,teamfight:8,magic:6}, Esmeralda:{frontline:8,sustain:9,dive:7,magic:8,teamfight:7,mobility:6,late:8},
    Ling:{dive:10,backline:10,mobility:10,burst:8,split:8,late:8,physical:9,objective:6}, Belerick:{frontline:10,peel:9,cc:8,antiDive:9,teamfight:9},
    Paquito:{burst:8,mobility:8,dive:7,physical:9,early:8,mid:8,cc:5,frontline:5}, Clint:{burst:8,poke:8,range:8,physical:10,early:8,mid:8,late:8},
    Novaria:{poke:10,range:10,vision:9,magic:10,waveclear:7,disengage:6,teamfight:7}, Barats:{frontline:10,objective:9,cc:8,sustain:8,early:8,mid:8,physical:6},
    Pharsa:{poke:9,range:9,burst:8,magic:10,waveclear:8,teamfight:8,mobility:6}, Valentina:{magic:9,burst:7,mobility:7,teamfight:9,waveclear:7,mid:9},
    Harith:{mobility:9,sustained:8,magic:9,dive:7,late:8,objective:7}, Hilda:{early:10,dive:8,frontline:7,burst:7,physical:8,vision:7},
    'Yi Sun-shin':{objective:9,sustained:8,vision:8,physical:9,late:9,mobility:6}
  };
  const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
  const enemySide=s=>s==='Blue'?'Red':'Blue';
  function profile(h){
    const roles=(h.roles||[]).map(x=>String(x).toLowerCase()), lanes=heroRoles(h);
    const p={frontline:2,engage:2,disengage:2,cc:2,burst:4,sustained:4,poke:2,sustain:2,mobility:4,waveclear:4,objective:4,backline:3,peel:2,antiDive:2,zone:2,range:3,early:5,mid:6,late:6,physical:4,magic:4,teamfight:5,split:3,dive:3,vision:2,disrupt:2};
    if(roles.some(r=>r.includes('tank')))Object.assign(p,{frontline:9,engage:7,cc:7,sustain:7,peel:7,antiDive:7,teamfight:8,burst:2,sustained:3});
    if(roles.some(r=>r.includes('support'))){p.engage=Math.max(p.engage,6);p.cc=Math.max(p.cc,6);p.peel=8;p.disengage=7;p.teamfight=8;p.vision=6;}
    if(roles.some(r=>r.includes('marksman')))Object.assign(p,{sustained:9,late:9,objective:8,physical:9,range:7,frontline:1,backline:2});
    if(roles.some(r=>r.includes('mage')))Object.assign(p,{magic:9,burst:7,poke:7,waveclear:8,teamfight:8,range:7,frontline:2});
    if(roles.some(r=>r.includes('assassin')))Object.assign(p,{burst:9,mobility:9,dive:9,backline:9,early:8,mid:9,frontline:1,cc:3});
    if(roles.some(r=>r.includes('fighter')))Object.assign(p,{frontline:6,sustain:6,dive:6,physical:8,early:7,mid:8,split:7,burst:6});
    if(lanes.includes('ROAM')){p.engage++;p.peel++;p.vision+=2} if(lanes.includes('JUNGLE')){p.objective+=2;p.mobility++} if(lanes.includes('MID')){p.waveclear++;p.teamfight++} if(lanes.includes('GOLD')){p.late++;p.objective++} if(lanes.includes('EXP')){p.frontline++;p.split++}
    Object.assign(p,PROFILES[h.name]||{}); Object.keys(p).forEach(k=>p[k]=Math.max(0,Math.min(10,p[k]))); return p;
  }
  function matchup(aHero,bHero){const a=profile(aHero),b=profile(bHero);let v=heroRoles(aHero).some(x=>heroRoles(bHero).includes(x))?1.5:0;v+=(a.cc-5)*Math.max(0,b.mobility-6)*.13;v+=(a.antiDive-5)*Math.max(0,b.dive-6)*.16;v+=(a.peel-5)*Math.max(0,b.backline-6)*.12;v+=(a.poke-5)*Math.max(0,5-b.range)*.10;v+=(a.sustain-5)*Math.max(0,b.poke-6)*.11;v+=(a.frontline-5)*Math.max(0,b.burst-7)*.08;v+=(a.burst-5)*Math.max(0,5-b.frontline)*.10;return Math.max(-5,Math.min(5,v));}
  function synergy(aHero,bHero){const a=profile(aHero),b=profile(bHero);let v=0;v+=Math.max(0,a.engage-6)*Math.max(0,b.burst-5)*.08;v+=Math.max(0,b.engage-6)*Math.max(0,a.burst-5)*.08;v+=Math.max(0,a.frontline-6)*Math.max(0,b.sustained-5)*.07;v+=Math.max(0,a.peel-6)*Math.max(0,b.sustained-6)*.08;v+=Math.max(0,b.cc-6)*Math.max(0,a.burst-5)*.06;v+=Math.max(0,a.cc-6)*Math.max(0,b.burst-5)*.06;return Math.min(5,v);}
  function scopedGames(){return (competitiveData.records||[]).filter(r=>state.scope==='Combined'||r.competition===state.scope)}
  function meta(h){const s=verifiedStats(h.name),games=Math.max(1,scopedGames().length);if(!s.sample)return {score:50,confidence:'INSUFFICIENT DATA',sample:0};const presence=Math.min(1,s.sample/games),shrunk=(s.wins+3)/(s.picks+6);return {score:clamp(35+presence*45+shrunk*20),confidence:s.sample>=15?'HIGH':s.sample>=6?'MEDIUM':'LOW',sample:s.sample};}
  function remaining(lane){return heroes.filter(h=>!usedNames().has(h.name)&&heroRoles(h).includes(lane)).length}
  function roleFit(h,step){const lanes=heroRoles(h),need=neededRoles(step.side);let x=45;if(lanes.some(l=>need.includes(l)))x+=30;if(lanes.length>1)x+=10;lanes.forEach(l=>{if(need.includes(l)&&remaining(l)<8)x+=8;if(need.includes(l)&&remaining(l)<4)x+=5});return clamp(x)}
  function composition(h,side){const team=sidePicks(side).map(profile),p=profile(h),avg=k=>team.length?team.reduce((a,x)=>a+x[k],0)/team.length:0;let x=50;if(avg('frontline')<4)x+=(p.frontline-5)*3;if(avg('engage')<4)x+=(p.engage-5)*2.5;if(avg('cc')<4)x+=(p.cc-5)*2;if(avg('waveclear')<5)x+=(p.waveclear-5)*1.5;if(avg('objective')<5)x+=(p.objective-5)*1.5;const phys=team.reduce((a,x)=>a+x.physical,0),mag=team.reduce((a,x)=>a+x.magic,0);if(phys>mag*1.8)x+=(p.magic-5)*2;if(mag>phys*1.8)x+=(p.physical-5)*2;return clamp(x)}
  function counter(h,step){const es=sidePicks(enemySide(step.side));if(!es.length)return 50;const vals=es.map(e=>matchup(h,e)),best=Math.max(...vals),avg=vals.reduce((a,b)=>a+b,0)/vals.length;return clamp(50+best*7+avg*4)}
  function allySynergy(h,step){const as=sidePicks(step.side);if(!as.length)return 50;const vals=as.map(a=>synergy(h,a));return clamp(48+(vals.reduce((x,y)=>x+y,0)/vals.length)*10)}
  function denial(h,step){const opp=enemySide(step.side),es=sidePicks(opp),lanes=heroRoles(h);let x=35;if(lanes.some(l=>neededRoles(opp).includes(l)))x+=25;if(es.length)x+=es.map(e=>synergy(h,e)).reduce((a,b)=>a+b,0)/es.length*7;if(step.type==='ban')x+=10;return clamp(x)}
  function secondPhase(h,step){if(state.actions.length<12)return 45;const target=step.type==='ban'?neededRoles(enemySide(step.side)):neededRoles(step.side),lanes=heroRoles(h);return clamp(50+(lanes.some(l=>target.includes(l))?25:0)+(lanes.length>1?8:0))}
  function analyze(h,step){
    const m=meta(h),rf=roleFit(h,step),ct=counter(h,step),sy=allySynergy(h,step),co=composition(h,step.side),de=denial(h,step),sp=secondPhase(h,step),fl=clamp(45+Math.max(0,heroRoles(h).length-1)*22),pos=step.side==='Blue'&&step.type==='pick'&&step.slot===1?62:50;
    const w=step.type==='ban'?{meta:.17,counter:.22,roleFit:.06,synergy:.03,composition:.03,denial:.30,secondPhase:.14,flex:.05}:{meta:.16,counter:.18,roleFit:.19,synergy:.15,composition:.16,denial:.06,secondPhase:.05,flex:.04,position:.01};
    const vals={meta:m.score,counter:ct,roleFit:rf,synergy:sy,composition:co,denial:de,secondPhase:sp,flex:fl,position:pos};let raw=0;Object.entries(w).forEach(([k,v])=>raw+=vals[k]*v);const score=Math.max(1,Math.min(99,Math.round(raw)));
    const enemies=sidePicks(enemySide(step.side)),allies=sidePicks(step.side);const good=enemies.map(e=>({n:e.name,v:matchup(h,e)})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v).slice(0,3).map(x=>x.n),threats=enemies.map(e=>({n:e.name,v:matchup(e,h)})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v).slice(0,3).map(x=>x.n),syn=allies.map(a=>({n:a.name,v:synergy(h,a)})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v).slice(0,3).map(x=>x.n);
    const type=step.type==='ban'?(ct>=70?'Direct Counter Ban':de>=70?'Denial Ban':sp>=70?'Role Target Ban':'Meta Ban'):(ct>=72?'Counter':sy>=72?'Synergy Pick':heroRoles(h).length>1?'Flex Pick':de>=72?'Denial Pick':'Pick');
    const reasons=[];if(ct>=65)reasons.push('strong matchup value into the current enemy draft');if(rf>=70)reasons.push('fills an important open role');if(sy>=65)reasons.push('combines well with current allies');if(co>=65)reasons.push('improves composition balance');if(de>=70)reasons.push('removes a valuable opponent option');if(sp>=70)reasons.push('high second-phase targeting value');if(m.sample)reasons.push(`${m.sample} verified scoped appearances`);if(!reasons.length)reasons.push('best contextual balance across role, matchup, and composition');
    return {score,type,confidence:m.confidence,reason:reasons.slice(0,3).join(' • '),components:vals,good,threats,syn};
  }
  window.mlbbCoachAnalyze=analyze;
  coachScore=(h,s)=>analyze(h,s).score; coachReason=(h,s)=>analyze(h,s).reason;
  topRecs=()=>{const s=currentStep();if(!s)return[];return heroes.filter(h=>!usedNames().has(h.name)).map(h=>({h,score:analyze(h,s).score,analysis:analyze(h,s)})).sort((a,b)=>b.score-a.score||a.h.name.localeCompare(b.h.name)).slice(0,5)};
  renderRecs=()=>{const root=document.getElementById('recs'),s=currentStep();if(!s){root.innerHTML='<div class="empty" style="grid-column:1/-1">Draft finished.</div>';return}root.innerHTML=topRecs().map(({h,analysis},i)=>`<div class="rec" data-name="${escapeHtml(h.name)}"><div class="rec-top">${h.icon_url?`<img src="${escapeHtml(h.icon_url)}" alt="">`:`<div class="mini-fallback">${escapeHtml(h.name[0])}</div>`}<div><div class="rec-name">#${i+1} ${escapeHtml(h.name)}</div><div class="rec-score">${analysis.score}/100 • ${escapeHtml(analysis.type)}</div></div></div><div class="rec-reason">${escapeHtml(analysis.reason)}<br><span style="color:#8ff0c5">Confidence: ${escapeHtml(analysis.confidence)}</span></div></div>`).join('');root.querySelectorAll('.rec').forEach(e=>e.onclick=()=>openHero(hByName(e.dataset.name)))};
  openHero=(h)=>{const s=currentStep()||{side:'Blue',type:'pick',slot:1},a=analyze(h,s),vs=verifiedStats(h.name),alts=topRecs().filter(x=>x.h.name!==h.name).slice(0,3).map(x=>x.h.name);document.getElementById('drawerBody').innerHTML=`<div class="drawer-head">${h.icon_url?`<img src="${escapeHtml(h.icon_url)}" alt="">`:`<div class="big-fallback">${escapeHtml(h.name[0])}</div>`}<div><h2>${escapeHtml(h.name)}</h2><p style="margin:4px 0">${escapeHtml((h.roles||[]).join(' / ')||'Hero')} • ${heroRoles(h).join(' / ')||'Role unresolved'}</p></div></div><div class="kv"><div><b>DRAFT PRIORITY</b><span>${a.score}/100</span></div><div><b>RECOMMENDATION TYPE</b><span>${escapeHtml(a.type)}</span></div><div><b>RECOMMENDED ROLE</b><span>${escapeHtml(heroRoles(h).join(' / ')||'Unresolved')}</span></div><div><b>CONFIDENCE</b><span>${escapeHtml(a.confidence)}</span></div></div><p><b>Why it is strong:</b> ${escapeHtml(a.reason)}</p><p><b>Good against:</b> ${escapeHtml(a.good.join(', ')||'No current enemy-specific advantage identified yet')}</p><p><b>Heroes that threaten it:</b> ${escapeHtml(a.threats.join(', ')||'No major current-draft threat identified')}</p><p><b>Synergy with current allies:</b> ${escapeHtml(a.syn.join(', ')||'No strong current ally synergy identified yet')}</p><p><b>Effect on team composition:</b> ${a.components.composition>=65?'Improves team structure, role coverage, or damage balance.':a.components.composition<45?'Creates composition tradeoffs; check frontline, engage, and damage balance before locking.':'Reasonable fit without a major structural gain or loss.'}</p><p><b>Alternative picks:</b> ${escapeHtml(alts.join(', ')||'None')}</p><div class="kv">${Object.entries(a.components).map(([k,v])=>`<div><b>${escapeHtml(k.toUpperCase())}</b><span>${Math.round(v)}/100</span></div>`).join('')}</div><p><b>OFFICIAL MATCH DATA:</b> ${vs.sample?`${vs.sample} scoped appearances found.`:'INSUFFICIENT DATA'}</p><p><b>CALCULATED DATA:</b> ${vs.sample?'Meta score and sample confidence use verified scoped records.':'INSUFFICIENT DATA'}</p><p><b>ANALYTICAL INFERENCE:</b> Counter, synergy, role fit, flex value, composition, denial value, second-phase targeting, role scarcity, and archetype interaction.</p><p><b>COACHING RECOMMENDATION:</b> ${escapeHtml(a.type)} — ${a.score}/100.</p>`;document.getElementById('drawer').classList.add('show')};
  const oldRenderAll=renderAll; renderAll=()=>{oldRenderAll();const note=document.getElementById('datasetNote');if(note&&!scopedGames().length)note.textContent='No verified professional records loaded. Meta statistics remain INSUFFICIENT DATA; recommendations below are explicitly analytical inference.';};
  const more=document.querySelector('#morePage .page-grid');if(more){const c=document.createElement('div');c.className='card';c.innerHTML='<h2>Professional Coach Engine</h2><p>Every action is recalculated using Meta Priority + Counter Strength + Ally Synergy + Role Fit + Flex Value + Composition Fit + Draft Position + Denial Value + Second-Phase Value + Sample Confidence.</p><p><b>OFFICIAL MATCH DATA</b> and <b>CALCULATED DATA</b> are only shown when verified records exist. Matchup, synergy, and composition logic are labeled <b>ANALYTICAL INFERENCE</b>.</p>';more.prepend(c)}
  renderAll();
})();
